journal_de_bord/urls.py
from django.urls import path

from . import views
# Créé un espace de nom 'app' pour compartimenter les urls (avec les noms donnés à chacune)
# Evite les conflits si plusieurs apps avec mêmes noms d'url
app_name = 'jdb'

urlpatterns = [
    # ex : /
    path('', views.home, name='home')
]

myFirstApp/urls.py
from django.urls import path

from . import views
# Créé un espace de nom 'app' pour compartimenter les urls (avec les noms donnés à chacune)
# Evite les conflits si plusieurs apps avec mêmes noms d'url
app_name = 'app'

urlpatterns = [
    # ex : /
    path('', views.IndexView.as_view(), name='index'),
    # ex: /5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tutoTest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include('myFirstApp.urls')),
    path('jdb/', include('journal_de_bord.urls')),
    path('admin/', admin.site.urls),
]

journal_de_bord/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Competence(models.Model):
    COMPETENCE_TYPE_CHOICES = [ 
        ('FRONT', 'Front-end'), 
        ('BACK', 'Back-end')
    ]
    COMPETENCE_DETAIL_CHOICES = [
        ('SEPARATOR', '--FRONT-END--'), 
        ('Maquetter une application', 'Maquetter une application'), 
        ('Réaliser une interface web statique et adaptable', 'Réaliser une interface web statique et adaptable'),
        ('Développer une interface web dynamique', 'Développer une interface web dynamique'),
        ('CMS FRONT', 'Réaliser une interface utilisateur avec une solution de gestion de contenu ou e-commerce'),
        ('SEPARATOR', '--BACK-END--'), 
        ('Créer une base de données', 'Créer une base de données'),
        ('Développer les composants d\'accès aux données', 'Développer les composants d\'accès aux données'),
        ('Développer la partie back-end d’une application web ou web mobile', 'Développer la partie back-end d’une application web ou web mobile'),
        ('CMS BACK', 'Elaborer et mettre en œuvre des composants dans une application de gestion de contenu ou e-commerce')
    ]
    competence_type = models.CharField(max_length = 200, choices = COMPETENCE_TYPE_CHOICES)
    competence_detail = models.CharField(max_length = 200, choices = COMPETENCE_DETAIL_CHOICES) 
    commentaires = models.TextField()
    
    def __str__(self):
        return self.competence_detail

class Techno(models.Model):
    nom = models.CharField(max_length=200)

    def __str__(self):
        return self.nom

class Etape(models.Model):
    nom = models.CharField(max_length=200)

    def __str__(self):
        return self.nom

class Entree_journal(models.Model):
    numero_semaine = models.IntegerField()
    numero_jour = models.IntegerField(default=0)
    date = models.DateField()
    a_faire = models.TextField(null=True, blank = True)
    fait = models.TextField(null=True, blank = True)
    problemes_rencontres = models.TextField(null=True, blank = True)
    resolution_problemes = models.TextField(null=True, blank = True)
    ressources_utilisees = models.TextField(null=True, blank = True)
    poursuite = models.TextField(null=True, blank = True)
    autre = models.TextField(null=True, blank = True)
    competences = models.ManyToManyField(Competence, blank=True)
    technos = models.ManyToManyField(Techno, blank=True)
    etape = models.ManyToManyField(Etape, blank=True)

    def __str__(self):
        str_date = self.date.strftime("%d-%m-%Y")
        sortie = str_date + " - Jour " + str(self.numero_jour)
        return sortie

myFirstApp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

class Result(models.Model):
    title = models.CharField(max_length=200)
    result = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

journal_de_bord/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    return HttpResponse("Bienvenue sur mon Journal de Bord")

myFirstApp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'myFirstApp/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        """Return the last five published questions (not including those set to be
        published in the future)."""
        return Question.objects.filter(
            pub_date__lte = timezone.now()
            ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'myFirstApp/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'myFirstApp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice']) 
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myFirstApp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('app:results', args=(question.id,)))
    

myFirstApp/templates/myFirstApp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detailed question</title>
</head>
<body>
    <h1> "{{ question.question_text }}" - id : {{question.id }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

   <form action="{% url 'app:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>

    <a href="{% url 'app:results' question.id %}"><button>See results for this question</button></a>
    
</body>
</html>

myFirstApp/templates/myFirstApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Latest questions</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'app:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available, sorry.</p>
    {% endif %}
</body>
</html>

myFirstApp/templates/myFirstApp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} : {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'app:detail' question.id %}">Vote for this question ?</a>
    
</body>
</html>